version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: gokigoki
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"

  web:
    build: .
    command: rails s
    environment:
      RAILS_ENV: "production"
      RACK_ENV: "production"
      GOKIAPP_DATABASE_PASSWORD: "gokigoki"
    volumes:
      - .:/gokiapp
    links:
      - db
